### ISSUE TITLE
Seeing unsupported operation while using this plugin

### ISSUE THREAD

**Issue by nyadav08** [idcmp/artifactory-secrets-plugin#1]
Hi,

I am not sure if you are aware of this issue but today I tried to use this plugin in our environment and after configuring everything I am getting below error when requesting a new token.
I am not a GO experts so couldn't perform much debugging and vault server running in debug mode doesn't give much info. I have verified from artifactory logs that requests didn't reached to artifactory so must be failing at vault side.

I followed this link to deploy the plugin on vault server running in -dev mode
https://learn.hashicorp.com/vault/developer/plugin-backends

Thanks in advance for your help and creating this plugin.

ran below commands
vault write artifactory/config/admin url=https://artifactory.naren.com/artifactory access_token=eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJra

vault write artifactory/roles/jenkins username="example-service-jenkins" scope="member-of-groups:readers" refreshable=true default_ttl=1h max_ttl=3h

bash-3.2$ vault write -force artifactory/token/jenkins
Error writing data to artifactory/token/jenkins: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/artifactory/token/jenkins
Code: 405. Errors:

* 1 error occurred:
	* unsupported operation

**Comment by idcmp** [comment]
Hi @nyadav08 ! 

Thanks for taking a look at this plugin, I just pushed my first semi-functional version over the weekend, so it's definitely not ready for production quite yet - You'll find the codebase is still littered with TODOs and FIXMEs. I'm glad there's interest! 

Use `vault read artifactory/token/jenkins` instead of `write`. I'll update the docs this evening.

You'll also find that revoke doesn't quite work properly yet, and refresh doesn't work the way I imagined it did with Artifactory, so I need to redo this.  

If you have time, please keep filing issues as you find them.

**Comment by idcmp** [comment]
Documentation updated. Thanks again!

**Comment by nyadav08** [comment]
Thanks for your help and providing the details.

Definitely we are not looking for production deployment yet but we would like to move forward in this direction so that vault can generate artifactory tokens. Its very nice that you have already developed this plugin and it has saved lot of effort from my side.

I will certainly open any issue if I come across and also if there is anything I can help you then please do let me know. Thanks

**Comment by idcmp** [comment]
What version of Artifactory are you running against?

**Comment by nyadav08** [comment]
I am running against 6.20.0
